# Generated by Django 3.0.3 on 2020-03-03 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10)),
                ('car_in', models.DateTimeField(auto_now_add=True)),
                ('car_out', models.DateTimeField(auto_now=True)),
                ('user_stat', models.NullBooleanField()),
                ('pay_val', models.CharField(blank=True, max_length=50, null=True)),
                ('car_stat', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=10)),
                ('ticket_num', models.CharField(max_length=10)),
                ('ticket_limit', models.DateField(default=datetime.datetime(2020, 5, 26, 20, 6, 53, 416617))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.User')),
            ],
        ),
    ]
